Repository getkirby/cli, pull requests merged in 2024-02, with the labels that each got.

#55 `clean:content` command
  .github/workflows/ci.yml
  .php-cs-fixer.dist.php
  commands/clean/content.php
Labels: type: feature 🎉

#59 New `clear:lock` command
  README.md
  commands/clear/lock.php
Labels: type: feature 🎉

#65 New debug mode
  README.md
  src/CLI/CLI.php
Labels: type: feature 🎉

#67 Switch linux commands to php functions
  commands/unzip.php
  src/CLI/CLI.php
Labels: type: refactoring :recycle:

#70 Use namespaced class names
  commands/make/_templates/model.php
Labels: type: enhancement ✨

#68 New `make:user` command
  README.md
  commands/make/user.php
Labels: type: feature 🎉

#71 New `upgrade` command
  README.md
  commands/upgrade.php
Labels: type: feature 🎉

#69 New `make:language` command
  README.md
  commands/make/language.php
Labels: type: feature 🎉

#62 New `backup` command
  README.md
  commands/backup.php
Labels: type: feature 🎉

#74 Call generator function for each loop
  commands/clean/content.php
Labels: type: bug 🐛

#63 New `plugin` commands
  README.md
  commands/plugin/install.php
  commands/plugin/remove.php
  commands/plugin/upgrade.php
Labels: type: feature 🎉
